# Generated by Django 6.0.3 on 2026-04-13 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Código ISBN inválido', regex='^(?:\\d{9}X|\\d{10}|\\d{13})$')])),
                ('sinopse', models.CharField(blank=True, max_length=650, null=True)),
                ('idioma', models.CharField(blank=True, max_length=2, null=True)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('avaliacoes', models.IntegerField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('publicacao', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('capa', models.CharField(blank=True, choices=[('dura', 'Capa dura'), ('mole', 'Capa mole'), ('sobre', 'Capa dura com sobrecapa'), ('orelhas', 'Capa mole com orelhas')], max_length=45, null=True)),
                ('faixa_etaria', models.CharField(blank=True, choices=[('livre', 'livre para todos'), ('adulto', 'adulto')], max_length=45, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('autores', models.ManyToManyField(blank=True, related_name='livro', to='core.autor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='core.categoria')),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='core.editora')),
            ],
        ),
    ]
