# Generated by Django 6.0.4 on 2026-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_livro_banner_livro_tipo_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
