# Generated by Django 6.0.4 on 2026-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_livro_subtitulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="categoria",
        ),
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ManyToManyField(
                blank=True, related_name="livro", to="core.categoria"
            ),
        ),
    ]
