# Generated by Django 6.0.4 on 2026-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_livro_categoria_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
