# Generated by Django 6.0.4 on 2026-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_livro_isbn_alter_livro_sinopse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
