# Generated by Django 6.0.4 on 2026-05-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_user_show_onboarding"),
        ("uploader", "0002_alter_image_uploaded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_foto",
                to="uploader.image",
            ),
        ),
    ]
