# Generated by Django 6.0.4 on 2026-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
