# Generated by Django 6.0.6 on 2026-06-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_google_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Biografia', max_length=255, null=True, verbose_name='biografia'),
        ),
    ]
