# Generated by Django 6.0.6 on 2026-07-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_livro_titulo'),
        ('core', '0013_user_bio'),
    ]

    operations = [
    ]
