# Generated by Django 6.0.6 on 2026-07-05 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_0011_alter_livro_titulo_0013_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quero_ler', 'Quero ler'), ('lendo', 'Lendo'), ('lido', 'Lido')], default='quero_ler', max_length=20)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
