# Generated by Django 6.0.6 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_livrousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='idioma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
