# Generated by Django 6.0.6 on 2026-08-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_livro_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrousuario',
            name='status',
            field=models.CharField(blank=True, choices=[('quero_ler', 'Quero ler'), ('lendo', 'Lendo'), ('lido', 'Lido')], max_length=20, null=True),
        ),
    ]
