# Generated by Django 6.0.6 on 2026-08-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_livrousuario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_leitura',
            field=models.PositiveIntegerField(default=10, help_text='Meta anual de livros para leitura', verbose_name='meta de leitura'),
        ),
    ]
