# Generated by Django 6.0.6 on 2026-10-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_meta_leitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('troca', 'Troca'), ('emprestimo', 'Empréstimo')], max_length=20)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom estado'), ('regular', 'Regular'), ('desgastado', 'Desgastado')], default='bom', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anuncio', to='core.livrousuario')),
            ],
            options={
                'verbose_name': 'anúncio',
                'verbose_name_plural': 'anúncios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
