# Generated by Django 6.0.4 on 2026-04-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
